version: '3.8'
services:
  postgres:
    container_name: "world_content_server_db"
    image: 'postgres:latest'
    restart: always
    user: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=world_content_server
    ports:
      - '5450:5432'
volumes:
  postgres_volume:
