name: Docs

on:
  pull_request:
    paths: ['docs/**']
  push:
    branches: [api]  

jobs:
  build:
    uses: decentraland/platform-actions/.github/workflows/apps-docs.yml@main
    with:
      service-name: worlds-content-server
    secrets: inherit
