name: API Docs

on:
  pull_request:
    paths: ['docs/**']
  push:
    branches: [main]
    paths: ['docs/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install tooling
        run: npm i -g @redocly/cli swagger-cli

      - name: Validate schema
        run: swagger-cli validate docs/openapi.yaml

      - name: Lint with Redocly
        run: redocly lint docs/openapi.yaml
        continue-on-error: true

      - name: Build JSON for Hugo
        run: redocly bundle docs/openapi.yaml -o docs/openapi.json --ext json

      - name: Build HTML (optional)
        run: redocly build-docs docs/openapi.yaml -o docs/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && vars.ENABLE_PAGES_DEPLOY == 'true'
    permissions: { pages: write, id-token: write }
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

