name: API Docs

on:
  pull_request:
    paths: ['docs/**']
  push:
    branches: [main]  

jobs:
  build:
    uses: decentraland/platform-actions/.github/workflows/apps-docs.yml@feat/upsert-api-spec-on-gitbook
    with:
      api-spec-file: docs/openapi.yaml
      api-spec-name: worlds-content-server
    secrets: inherit
