name: mariano-aps-build

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: worlds_content_server
          POSTGRES_PASSWORD: pass1234
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: install
        run: yarn install --frozen-lockfile
      - name: create .env
        run: echo "" >> .env
      - name: build
        run: yarn build
      - name: test
        run: yarn test
        env:
          PG_COMPONENT_PSQL_CONNECTION_STRING: postgres://postgres:pass1234@localhost/worlds_content_server

